DROP SEQUENCE MEMBERSEQ;
DROP TABLE MEMBERBOARD;

CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MEMBERBOARD(
	MEMBER_CODE NUMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(100) NOT NULL,
	MEMBER_ID VARCHAR2(100) UNIQUE,
	MEMBER_PW VARCHAR2(100) NOT NULL,
	MEMBER_EMAIL VARCHAR2(100) NOT NULL,
	MEMBER_PHONE VARCHAR2(100) NOT NULL,
	MEMBER_ADDR VARCHAR2(100) NOT NULL
);

INSERT INTO MEMBERBOARD
VALUES(MEMBERSEQ.NEXTVAL, '관리자', 'ADMIN', '1234', 'ADMIN@ADMIN.COM', '010-1111-2222', '서울시 중랑구');

SELECT * FROM MEMBERBOARD;